### ISSUE TITLE
What's the web address for this information?

### ISSUE THREAD

**Issue by lechner** [nomeata/hpvt#1]
Hi,

Is the information generated by this code published anywhere?

I only found an [outdated page](https://people.debian.org/~nomeata/hackagevsdebian.html) on `people.debian.org`. Thanks!

Kind regards
Felix Lechner

**Comment by nomeata** [comment]
This tool is also used to upload data to hackage.org, to fill the “Distribution” data e.g. seen on https://hackage.haskell.org/package/arbtt.

I kinda let the installation on people.debian.org bitrot a bit, and the cronjob is failing. I would love if someone else would take this over, maybe modernizing the setup.

**Comment by lechner** [comment]
Would it be better to retrieve the information from Hackage, and focus the tool on updating the metadata there?

**Comment by lechner** [comment]
I realize now that my comment was somewhat backwards.

**Comment by nomeata** [comment]
You mean hackage pulling the data? That was not desirable by the hackage maintainers back then, they wanted a push solution.

**Comment by lechner** [comment]
Hi, how did the now-deprecated Haskell Platform figure into the display in the web page, please?

**Comment by lechner** [comment]
Never mind. I figured it out. I updated Debian's package map on Hackage.

The [HTML output](https://people.debian.org/~lechner/output.html) works too, but I have not automated it yet.

**Comment by lechner** [comment]
Or with some [modest styling](https://hackage.debian.net/).

**Comment by nomeata** [comment]
Great, thanks a lot!

**Comment by lechner** [comment]
Would you consider a merge request with my proposed changes?

**Comment by lechner** [comment]
If you would like someone to take over, I am happy to take it.

My first steps would be to rebrand it as `hackage-tracker` (HPV means something else here) and package it for Debian for automatic deployment somewhere.

Please just let me know. Thanks!

**Comment by nomeata** [comment]
Yes, please take over and do as you see fit! Thanks a lot.

I'll archive this repository later with a pointer to yours.

**Comment by lechner** [comment]
Hi Joachim,

Your project is now hosted [on Salsa](https://salsa.debian.org/haskell-team/hackage-tracker). Happy to give it back anytime. Thanks!

Kind regards
Felix Lechner
